name: Run Jest Tests and Coverage Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Run Jest Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 23
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Run Jest Tests
      run: |
        npm test -- --coverage
      working-directory: apps/my-first-app

  coverage_report:
    name: Generate Coverage Report
    needs: testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1

    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v4
      with:
        coverage-files: coverage/lcov.info
        minimum-coverage: 90
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: apps/my-first-app
        update-comment: true
